[package]
name = "themelio-client"
version = "0.1.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow="1"
rustyline = "7.1.0"
sled="0.34.6"
smol="1"
smol-timeout="0.6.0"
structopt = "0.3.18"

blkstructs={path="../../libs/blkstructs"}
#tmelcrypt={path="../../libs/tmelcrypt"}
#melnet={path="../../libs/melnet"}
#autosmt={path="../../libs/autosmt"}
#stdcode={path="../../libs/stdcode"}
nodeprot={path="../../libs/nodeprot"}
#neosymph={path="../../libs/neosymph"}