---

- name: 'Create themelio-node image'
  hosts: themelio_node
  become: yes

  tasks:
    - name: Add Docker apt key.
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repositories to apt
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
        state: present

    - name: Install docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: latest

    - name: Install docker-compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: a+x

    - name: Enable the docker service
      ansible.builtin.service:
        name: docker
        enabled: yes

    - name: Add the debian user to the docker group
      ansible.builtin.user:
        name: debian
        groups: docker
        append: yes

    - name: Start the docker service
      ansible.builtin.service:
        name: docker
        state: started

    - name: Create the compose directory
      ansible.builtin.file:
        path: /home/debian/compose
        state: directory

    - name: Copy the docker-compose template to the server
      ansible.builtin.template:
        src: docker-compose.testnet.yml.j2
        dest: /home/debian/compose/docker-compose.yml

    - name: Copy the themelio-node systemd service file onto the server
      ansible.builtin.copy:
        src: themelio-node.service
        dest: /usr/lib/systemd/system/themelio-node.service

    - name: Enable and start the themelio-node service
      ansible.builtin.systemd:
        name: themelio-node
        daemon_reload: yes
        state: started
        enabled: yes