---

- name: 'Create themelio-node image'
  hosts: themelio-node
  become: yes

  tasks:
    - name: Install docker and docker-compose
      community.general.pacman:
        name:
          - docker
          - docker-compose
        state: latest

    - name: Enable the docker service
      ansible.builtin.service:
        name: docker
        enabled: yes

    - name: Add the arch user to the docker group
      ansible.builtin.user:
        name: arch
        groups: docker
        append: yes

    - name: Start the docker service
      ansible.builtin.service:
        name: docker
        state: started

    - name: Create the compose directory
      ansible.builtin.file:
        path: /home/arch/compose
        state: directory

    - name: Copy the docker-compose template to the server
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: /home/arch/compose/docker-compose.yml

    - name: Copy the themelio-node systemd service file onto the server
      ansible.builtin.copy:
        src: themelio-node.service
        dest: /usr/lib/systemd/system/themelio-node.service

    - name: Enable and start the themelio-node service
      ansible.builtin.systemd:
        name: themelio-node
        daemon_reload: yes
        state: started
        enabled: yes