---

- hosts: localhost

  tasks:
    - name: Install docker and docker-compose
      community.general.pacman:
        name:
          - docker
          - docker-compose
        state: latest
      become: yes

    - name: Enable the docker service
      ansible.builtin.service:
        name: docker
        enabled: yes
      become: yes

    - name: Add the arch user to the docker group
      ansible.builtin.user:
        name: arch
        groups: docker
        append: yes
      become: yes

    - name: Start the docker service
      ansible.builtin.service:
        name: docker
        state: started
      become: yes

    - name: Start the themelio-node image
      community.docker.docker_container:
        name: themelio-node
        image: ghcr.io/themeliolabs/themelio-node:latest
        command: ["--strategy rolling --url https://bldr.habitat.sh"]
        state: started
        volumes: themelio-node:/hab/svc/themelio-node/data
        container_default_behavior: compatibility
      become: yes