name: BuildAndPublish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Apt
        run: sudo apt update

      - name: Install TzData
        run: env DEBIAN_FRONTEND="noninteractive" sudo apt install -y tzdata

      - name: Install OpenStack, Packer, And envsubst
        run: sudo apt install -y python3-openstackclient python3-novaclient packer jq gettext-base

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Biome
        env:
          BIOME_VERSION: "1.6.300"
        run: curl -L "https://github.com/biome-sh/biome/releases/download/$BIOME_VERSION/bio-$BIOME_VERSION-x86_64-linux.tar.gz" | tar zxv

      - name: Install Biome
        run: sudo mv bio /usr/local/bin/bio

      - name: Import Public Key
        env:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
        run: echo "$BIOME_PUBLIC_KEY" | bio origin key import

      - name: Import Public Key (sudo)
        env:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
        run: echo "$BIOME_PUBLIC_KEY" | sudo bio origin key import

      - name: Import Signing Key
        env:
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
        run: echo "$BIOME_SIGNING_KEY" | bio origin key import

      - name: Import Signing Key (sudo)
        env:
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
        run: echo "$BIOME_SIGNING_KEY" | sudo bio origin key import

      - name: Build, Run BATS Tests, Publish Artifact And Mark As Stable, Export And Publish Docker Image
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          HAB_BLDR_URL: "https://bldr.habitat.sh"
          BIOME_BLDR_URL: "https://bldr.biome.sh"
          BIOME_AUTH_TOKEN: ${{ secrets.BIOME_AUTH_TOKEN }}
          HABITAT_AUTH_TOKEN: ${{ secrets.HABITAT_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_HEALTH_CHECK: true
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        run: cd biome && ./themelio-node/scripts/ci-publish.sh