name: BuildAndTestTestNet

on:
  pull_request:
    branches:
      - testnet

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-testnet:
    runs-on: self-hosted

    container:
      image: ghcr.io/themeliolabs/biome:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Import Biome Public Key
        env:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
        run: echo "$BIOME_PUBLIC_KEY" | bio origin key import

      - name: Import Biome Signing Key
        env:
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
        run: echo "$BIOME_SIGNING_KEY" | bio origin key import

      - name: Build, Run BATS Tests
        env:
          HAB_ORIGIN: "themelio"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROMTAIL_USERNAME: ${{ secrets.PROMTAIL_USERNAME }}
          PROMTAIL_PASSWORD: ${{ secrets.PROMTAIL_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          NETWORK_TO_BUILD: "testnet"
        run: ./biome/themelio-node/scripts/ci-test.sh