name: BuildAndTestMainNet

on:
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-mainnet:
    runs-on: self-hosted

    container:
      image: ghcr.io/themeliolabs/biome:latest

    steps:
      - uses: actions/checkout@v2

#      - uses: themeliolabs/actions-biome@v1
#        with:
#          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
#          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Download Biome
        env:
          BIOME_VERSION: "1.6.372"
        run: curl -L "https://github.com/biome-sh/biome/releases/download/v$BIOME_VERSION/bio-$BIOME_VERSION-x86_64-linux.tar.gz" | tar zxv

      - name: Install Biome
        run: mv bio /usr/local/bin/bio

      - name: Remove Curl
        run: apt remove -y curl

      - name: Import Biome Public Key
        env:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
        run: echo "$BIOME_PUBLIC_KEY" | bio origin key import

      - name: Import Biome Signing Key
        env:
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
        run: echo "$BIOME_SIGNING_KEY" | bio origin key import

      - name: Build, Run BATS Tests
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROMTAIL_USERNAME: ${{ secrets.PROMTAIL_USERNAME }}
          PROMTAIL_PASSWORD: ${{ secrets.PROMTAIL_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          NETWORK_TO_BUILD: "mainnet"
        run: ./biome/themelio-node/scripts/ci-test.sh