name: BuildAndTestMainNet

on:
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-mainnet:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Fix Directory Permissions
        run: sudo chown -R $(whoami):$(id -ng) /hab

#      - name: Echo
#        env:
#          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
#        run: echo "$AWS_DEFAULT_REGION"

#      - name: Cache Biome
#        uses: actions/cache@v2
#        env:
#          CACHE_NAME: cache-biome
#        with:
#          path: |
#            ~/.hab/cache/artifacts
#            /hab/cache/artifacts
#            /hab/pkgs
#          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('biome/themelio-node/plan-debug.sh') }}
#          restore-keys: |
#            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
#            ${{ runner.os }}-build-
#            ${{ runner.os }}-

#      - name: Set Biome Origin
#        run: echo "HAB_ORIGIN=themelio" >> $GITHUB_ENV
#
#      - name: Set Biome Public Key
#        run: env BIOME_PUBLIC_KEY=${{ secrets.BIOME_PUBLIC_KEY }} echo "BIOME_PUBLIC_KEY=$BIOME_PUBLIC_KEY" >> $GITHUB_ENV
#
#      - name: Set GitHub Token
#        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
#
#      - name: Set Promtail Username
#        run: echo "PROMTAIL_USERNAME=${{ secrets.PROMTAIL_USERNAME }}" >> $GITHUB_ENV
#
#      - name: Set Promtail Password
#        run: echo "PROMTAIL_PASSWORD=${{ secrets.PROMTAIL_PASSWORD }}" >> $GITHUB_ENV
#
#      - name: Set AWS Access Key ID
#        run: echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
#
#      - name: Set AWS Secret Access Key
#        run: echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
#
#      - name: Set AWS Default Region
#        run: echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> $GITHUB_ENV
#
#      - name: Set Network To Build
#        run: echo "NETWORK_TO_BUILD=mainnet" >> $GITHUB_ENV

      - name: Build, Run BATS Tests
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROMTAIL_USERNAME: ${{ secrets.PROMTAIL_USERNAME }}
          PROMTAIL_PASSWORD: ${{ secrets.PROMTAIL_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          NETWORK_TO_BUILD: "mainnet"
        run: ./biome/themelio-node/scripts/ci-test.sh