name: BuildAndPublishTestNet

on:
  push:
    branches:
      - testnet

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-publish-testnet:
    runs-on: self-hosted

    container:
      image: ghcr.io/themeliolabs/biome:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Log Into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Import Biome Public Key
        env:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
        run: echo "$BIOME_PUBLIC_KEY" | bio origin key import

      - name: Import Biome Signing Key
        env:
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
        run: echo "$BIOME_SIGNING_KEY" | bio origin key import

      - name: Build, Publish Artifact And Mark As Stable, Export And Publish Docker Image, Create Packer Images
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          HAB_BLDR_URL: "https://bldr.habitat.sh"
          BIOME_BLDR_URL: "https://bldr.biome.sh"
          BIOME_AUTH_TOKEN: ${{ secrets.BIOME_AUTH_TOKEN }}
          HABITAT_AUTH_TOKEN: ${{ secrets.HABITAT_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROMTAIL_USERNAME: ${{ secrets.PROMTAIL_USERNAME }}
          PROMTAIL_PASSWORD: ${{ secrets.PROMTAIL_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          NETWORK_TO_BUILD: "testnet"
        run: ./biome/themelio-node/scripts/ci-publish.sh