name: BuildAndTestMainNet

on:
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: "/usr/local/cargo/"
  RUSTUP_HOME: "/usr/local/rustup"
  SCCACHE_DIR: "/usr/local/sccache"
  RUSTC_WRAPPER: "/usr/local/bin/sccache"

jobs:
  musl-build-mainnet:

    runs-on: self-hosted

    container:
      image: rust:latest
      volumes:
        - /var/lib/docker:/var/lib/docker
        - /usr/local/cargo/git:/usr/local/cargo/git
        - /usr/local/cargo/registry:/usr/local/cargo/registry
        - /usr/local/sccache:/usr/local/sccache
        - /usr/local/rustup:/usr/local/rustup
        - /var/lib/docker:/var/lib/docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Apt
        run: apt update

      - name: Install Musl
        run: apt -y install musl musl-tools

      - uses: themeliolabs/actions-sccache@v1

      - uses: themeliolabs/actions-mold@v1

      - name: Add Default Toolchain
        run: rustup default stable

      - name: Add Musl Target Triple
        run: rustup target add x86_64-unknown-linux-musl

      - name: Run Musl Build
        run: mold --run cargo build --target x86_64-unknown-linux-musl --features metrics --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: themelio-node-mainnet-dev
          path: target/x86_64-unknown-linux-musl/debug/themelio-node



  build-and-test-mainnet:
    runs-on: self-hosted

    needs:
      - musl-build-mainnet

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: themelio-node-mainnet-dev
          path: docker/

      - name: Install Yq
        run: pip install yq

      - name: Create Version Environment Variable
        run: echo "THEMELIO_NODE_VERSION=$(cat Cargo.toml | tomlq .package.version | tr -d '"')" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t "ghcr.io/themeliolabs/themelio-node:${THEMELIO_NODE_VERSION}" docker/



#      - name: Build, Run BATS Tests
#        env:
#          HAB_ORIGIN: "themelio"
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PROMTAIL_USERNAME: ${{ secrets.PROMTAIL_USERNAME }}
#          PROMTAIL_PASSWORD: ${{ secrets.PROMTAIL_PASSWORD }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
#          NETWORK_TO_BUILD: "mainnet"
#        run: ./biome/themelio-node/scripts/ci-test.sh