name: BuildAndTestMainNet

on:
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  SCCACHE_DIR: "/usr/local/sccache"
  RUSTC_WRAPPER: "/usr/local/bin/sccache"

jobs:
  build-and-test-mainnet:
    runs-on: self-hosted

    container:
      image: ghcr.io/themeliolabs/biome:latest
      options: --privileged
      volumes:
        - /var/lib/docker:/var/lib/docker
        - /usr/local/sccache:/usr/local/sccache
        - /hab/cache/artifacts:/hab/cache/artifacts
        - /hab/pkgs:/hab/pkgs

    steps:
      - uses: actions/checkout@v3

      - name: Import Biome Public Key
        env:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
        run: echo "$BIOME_PUBLIC_KEY" | bio origin key import

      - name: Import Biome Signing Key
        env:
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
        run: echo "$BIOME_SIGNING_KEY" | bio origin key import

      - name: Import Biome Public Key (root)
        env:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
        run: echo "$BIOME_PUBLIC_KEY" | sudo bio origin key import --cache-key-path /hab/cache/keys

      - name: Import Biome Signing Key (root)
        env:
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
        run: echo "$BIOME_SIGNING_KEY" | sudo bio origin key import --cache-key-path /hab/cache/keys

      - name: List
        run: ls -la ~/.hab/cache/keys

      - name: List (root)
        run: sudo ls -la /hab/cache/keys

#      - name: Copy SCCache To Current Directory
#        run: sudo cp -a /usr/local/sccache sccache
#
#      - name: Build, Run BATS Tests
#        env:
#          HAB_ORIGIN: "themelio"
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PROMTAIL_USERNAME: ${{ secrets.PROMTAIL_USERNAME }}
#          PROMTAIL_PASSWORD: ${{ secrets.PROMTAIL_PASSWORD }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
#          NETWORK_TO_BUILD: "mainnet"
#        run: ./biome/themelio-node/scripts/ci-test.sh
#
#      - name: Remove Old Cache
#        run: sudo rm -rf /usr/local/sccache/*
#
#      - name: Copy SCCache From Build
#        run: sudo cp -a sccache/. /usr/local/sccache/