name: BuildAndPublishTestNet

on:
  push:
    branches:
      - testnet

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-publish-testnet:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Fix Directory Permissions
        run: sudo chown -R $(whoami):$(id -ng) /hab

      - name: Update Apt
        run: sudo apt update

      - name: Install Curl
        run: sudo apt install -y curl

      - name: Add Hashicorp Key
        run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

      - name: Add Hashicorp Repository
        run: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

      - name: Update Apt
        run: sudo apt update

      - name: Install TzData
        run: env DEBIAN_FRONTEND="noninteractive" sudo apt install -y tzdata

      - name: Install Gettext, Packer, Pip, And Ansible
        run: sudo apt install -y gettext packer pip ansible

      - name: Install YQ
        run: pip install yq

      #      - name: Cache Biome
      #        uses: actions/cache@v2
      #        env:
      #          CACHE_NAME: cache-biome
      #        with:
      #          path: |
      #            ~/.hab/cache/artifacts
      #            /hab/cache/artifacts
      #            /hab/pkgs
      #          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('biome/themelio-node/plan-debug.sh') }}
      #          restore-keys: |
      #            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
      #            ${{ runner.os }}-build-
      #            ${{ runner.os }}-

      - name: Build, Publish Artifact And Mark As Stable, Export And Publish Docker Image, Create Packer Images
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          HAB_BLDR_URL: "https://bldr.habitat.sh"
          BIOME_BLDR_URL: "https://bldr.biome.sh"
          BIOME_AUTH_TOKEN: ${{ secrets.BIOME_AUTH_TOKEN }}
          HABITAT_AUTH_TOKEN: ${{ secrets.HABITAT_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROMTAIL_USERNAME: ${{ secrets.PROMTAIL_USERNAME }}
          PROMTAIL_PASSWORD: ${{ secrets.PROMTAIL_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          NETWORK_TO_BUILD: "testnet"
        run: ./biome/themelio-node/scripts/ci-publish.sh