name: MuslBuild

on:
  pull_request:
    branches:
      - master
      - testnet

env:
  CARGO_TERM_COLOR: always

jobs:
  musl-build:

    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v3

#      - uses: actions/cache@v2
#        with:
#          path: |
#            ~/.cargo/bin/
#            ~/.cargo/registry/index/
#            ~/.cargo/registry/cache/
#            ~/.cargo/git/db/
#            target/
#          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Update Apt
        run: sudo apt update

      - name: Install Musl
        run: sudo apt install -y musl musl-tools

      - name: Install Rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Add Rustup To Path
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Add Musl Target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Run Musl Build
        run: cargo build --locked --target x86_64-unknown-linux-musl --features metrics --verbose