name: TestBuildAndPublish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

#      - name: Update Apt
#        run: sudo apt update
#
#      - name: Install Musl
#        run: sudo apt install -y musl musl-tools
#
#      - name: Add Musl Target
#        run: rustup target add x86_64-unknown-linux-musl
#
#      - name: Run Musl Tests
#        run: cargo test --locked --target x86_64-unknown-linux-musl --verbose

      - name: Download Biome
        env:
          BIOME_VERSION: "1.6.300"
        run: curl -L "https://github.com/biome-sh/biome/releases/download/$BIOME_VERSION/bio-$BIOME_VERSION-x86_64-linux.tar.gz" | tar zxv

      - name: Install Biome
        run: sudo mv bio /usr/local/bin/bio

      - name: Import Public Key
        env:
          BIOME_PUBLIC_KEY: ${{secrets.BIOME_PUBLIC_KEY}}
        run: echo "$BIOME_PUBLIC_KEY" | bio origin key import

      - name: Import Signing Key
        env:
          BIOME_SIGNING_KEY: ${{secrets.BIOME_SIGNING_KEY}}
        run: echo "$BIOME_SIGNING_KEY" | bio origin key import

#      - name: Download Public Key
#        env:
#          HAB_BLDR_URL: "https://bldr.biome.sh"
#        run: sudo bio origin key download themelio

      - name: Build Plan
        env:
#          DO_CHECK: true
          HAB_ORIGIN: "themelio"
        run: cd biome && bio pkg build themelio-node

      - name: Run BATS Tests
        env:
          SKIPBUILD: true
          HAB_ORIGIN: "themelio"
        run: cd biome && sudo ./themelio-node/tests/test.sh


# /src/results/last_build.env


# I need to duplicate the publish artifacts step for https://bldr.habitat.sh as well

#      - name: Publish Artifact
#        env:
#          HAB_BLDR_URL: "https://bldr.biome.sh"
#          HAB_AUTH_TOKEN: ${{secrets.BIOME_AUTH_TOKEN}}
#          HAB_ORIGIN: "themelio"
#        run: bio pkg upload /path/to/hart/file

#      - name: Mark Release As Stable In The Builder

#      - name: Export Docker Image
#        env:
#          SKIPBUILD: true
#        run: bio pkg export container /path/to/hart/file