name: TestAndBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: apt update && apt -y install musl && rustup target add x86_64-unknown-linux-musl && cargo build --target x86_64-unknown-linux-musl --verbose
