name: TestAndBuild

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Cache Biome
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-biome
        with:
          path: ~/.hab/cache
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('biome/themelio-node/plan-debug.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build, Run BATS Tests
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./biome/themelio-node/scripts/ci-test.sh