name: TestBuildAndPublish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update Apt
        run: sudo apt update

#      - name: Create Biome Key Path
#        run: sudo mkdir -p /root/.hab/cache/keys

#      - name: Create Biome Public Key
#        run: echo ${{ secrets.BIOME_PUBLIC_KEY }} | base64 -d > /tmp/themelio-20210708170207.pub
#      - name: Move Biome Public Key
#        run: sudo mv /tmp/themelio-20210708170207.pub /hab/cache/keys/themelio-20210708170207.pub

#      - name: Create Biome Signing Key
#        run: echo ${{ secrets.BIOME_SIGNING_KEY }} | base64 -d > /tmp/themelio-20210708170207.sig.key
#      - name: Move Biome Signing Key
#        run: sudo mv /tmp/themelio-20210708170207.sig.key /hab/cache/keys/themelio-20210708170207.sig.key



#      - name: Create Biome Public Key
#        run: 'echo "$BIOME_PUBLIC_KEY" > /tmp/themelio-20210708170207.pub'
#        shell: bash
#        env:
#          BIOME_PUBLIC_KEY: ${{secrets.BIOME_PUBLIC_KEY}}
#      - name: Move Biome Public Key
#        run: sudo mv /tmp/themelio-20210708170207.pub /root/.hab/cache/keys/themelio-20210708170207.pub


#      - name: Create Biome Signing Key
#        run: 'echo "$BIOME_SIGNING_KEY" > /tmp/themelio-20210708170207.sig.key'
#        shell: bash
#        env:
#          BIOME_SIGNING_KEY: ${{secrets.BIOME_SIGNING_KEY}}
#      - name: Move Biome Signing Key
#        run: sudo mv /tmp/themelio-20210708170207.sig.key /root/.hab/cache/keys/themelio-20210708170207.sig.key



      - name: Download Biome
        run: curl -L https://github.com/biome-sh/biome/releases/download/1.6.300/bio-1.6.300-x86_64-linux.tar.gz | tar zxv
      - name: Install Biome
        run: sudo mv bio /usr/local/bin/bio

      - name: Import Public Key
        env:
          BIOME_PUBLIC_KEY: ${{secrets.BIOME_PUBLIC_KEY}}
        run: echo "BIOME_PUBLIC_KEY" | sudo bio origin key import

      - name: Import Signing Key
        env:
          BIOME_SIGNING_KEY: ${{secrets.BIOME_SIGNING_KEY}}
        run: echo "$BIOME_SIGNING_KEY" | sudo bio origin key import

#      - name: Download Public Key
#        env:
#          HAB_BLDR_URL: "https://bldr.biome.sh"
#        run: bio origin key download themelio

      - name: Build plan
        env:
          HAB_BLDR_URL: "https://bldr.biome.sh"
          DO_CHECK: true
          HAB_AUTH_TOKEN: ${{secrets.HAB_AUTH_TOKEN}}
          HAB_ORIGIN: "themelio"
        run: cd biome && sudo bio pkg build themelio-node



#      - name: Run tests
#        run: cd biome && env SKIPBUILD=true sudo ./themelio-node/tests/test.sh