name: TestBuildAndPublish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update Apt
        run: sudo apt update

      - name: Download Biome
        env:
          BIOME_VERSION: "1.6.300"
        run: curl -L "https://github.com/biome-sh/biome/releases/download/$BIOME_VERSION/bio-$BIOME_VERSION-x86_64-linux.tar.gz" | tar zxv
      - name: Install Biome
        run: sudo mv bio /usr/local/bin/bio

      - name: Import Public Key
        env:
          BIOME_PUBLIC_KEY: ${{secrets.BIOME_PUBLIC_KEY}}
        run: echo "$BIOME_PUBLIC_KEY" | bio origin key import

      - name: Import Signing Key
        env:
          BIOME_SIGNING_KEY: ${{secrets.BIOME_SIGNING_KEY}}
        run: echo "$BIOME_SIGNING_KEY" | bio origin key import

#      - name: Download Public Key
#        env:
#          HAB_BLDR_URL: "https://bldr.biome.sh"
#        run: sudo bio origin key download themelio

#      - name: Create Keys Directory
#        run: sudo mkdir -p /root/.hab/cache/keys
#
#      - name: Copy Keys
#        run: sudo cp /hab/cache/keys/* /root/.hab/cache/keys
#
#      - name: List Keys Directory
#        run: sudo ls -la /root/.hab/cache/keys

      - name: Build plan
        env:
#          HAB_BLDR_URL: "https://bldr.biome.sh"
          DO_CHECK: true
          HAB_AUTH_TOKEN: ${{secrets.HAB_AUTH_TOKEN}}
          HAB_ORIGIN: "themelio"
        run: cd biome && bio pkg build themelio-node

      - name: Run tests
        env:
          SKIPBUILD: true
        run: cd biome && sudo ./themelio-node/tests/test.sh