name: Tests

on:
  pull_request:
    branches:
      - master
      - testnet

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: "/usr/local/cargo/"
  RUSTUP_HOME: "/usr/local/rustup"
  SCCACHE_DIR: "/usr/local/sccache"
  RUSTC_WRAPPER: "/usr/local/bin/sccache"

jobs:
  tests:
    runs-on: self-hosted

    container:
      image: rust:latest
      volumes:
        - /var/lib/docker:/var/lib/docker
        - /usr/local/cargo/git:/usr/local/cargo/git
        - /usr/local/cargo/registry:/usr/local/cargo/registry
        - /usr/local/sccache:/usr/local/sccache
        - /usr/local/rustup:/usr/local/rustup
        - /var/lib/docker:/var/lib/docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: themeliolabs/actions-sccache@v1

      - uses: themeliolabs/actions-mold@v1

      - name: Add Default Toolchain
        run: rustup default stable

      - name: Run tests
        run: mold --run cargo test --target=x86_64-unknown-linux-gnu --verbose