name: TestAndBuild

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Apt
        run: sudo apt update

      - name: Install Musl
        run: sudo apt install -y musl musl-tools

      - name: Add Musl Target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Run Musl Tests
        run: cargo test --locked --target x86_64-unknown-linux-musl --features metrics --verbose

      - name: Download Biome
        env:
          BIOME_VERSION: "1.6.300"
        run: curl -L "https://github.com/biome-sh/biome/releases/download/$BIOME_VERSION/bio-$BIOME_VERSION-x86_64-linux.tar.gz" | tar zxv

      - name: Install Biome
        run: sudo mv bio /usr/local/bin/bio

      - name: Remove Curl To Prevent Biome Conflicts
        run: sudo apt remove -y curl

      - name: Import Public Key
        env:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
        run: echo "$BIOME_PUBLIC_KEY" | bio origin key import

      - name: Import Public Key (sudo)
        env:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
        run: echo "$BIOME_PUBLIC_KEY" | sudo bio origin key import

      - name: Import Signing Key
        env:
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
        run: echo "$BIOME_SIGNING_KEY" | bio origin key import

      - name: Import Signing Key (sudo)
        env:
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
        run: echo "$BIOME_SIGNING_KEY" | sudo bio origin key import

      - name: Build, Run BATS Tests
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./biome/themelio-node/scripts/ci-test.sh