name: TestBuildAndPublish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update Apt
        run: sudo apt update
      - name: Create Biome Key Path
        run: sudo mkdir -p /hab/cache/keys

#      - name: Create Biome Public Key
#        run: echo ${{ secrets.BIOME_PUBLIC_KEY }} | base64 -d > /tmp/themelio-20210708170207.pub
#      - name: Move Biome Public Key
#        run: sudo mv /tmp/themelio-20210708170207.pub /hab/cache/keys/themelio-20210708170207.pub

#      - name: Create Biome Signing Key
#        run: echo ${{ secrets.BIOME_SIGNING_KEY }} | base64 -d > /tmp/themelio-20210708170207.sig.key
#      - name: Move Biome Signing Key
#        run: sudo mv /tmp/themelio-20210708170207.sig.key /hab/cache/keys/themelio-20210708170207.sig.key


      - name: Create Biome Public Key
        run: 'echo "$BIOME_PUBLIC_KEY" > /tmp/themelio-20210708170207.pub'
        shell: bash
        env:
          BIOME_PUBLIC_KEY: ${{secrets.BIOME_PUBLIC_KEY}}
      - name: Move Biome Public Key
        run: sudo mv /tmp/themelio-20210708170207.pub /hab/cache/keys/themelio-20210708170207.pub


      - name: Download Biome
        run: curl -L https://github.com/biome-sh/biome/releases/download/1.6.300/bio-1.6.300-x86_64-linux.tar.gz | tar zxv
      - name: Install Biome
        run: sudo mv bio /usr/local/bin/bio
      - name: Build plan
        run: cd biome && env DO_CHECK=true sudo bio pkg build themelio-node
#      - name: Run tests
#        run: cd biome && env SKIPBUILD=true sudo ./themelio-node/tests/test.sh